### ISSUE TITLE
Jedi is not pinned to 0.9.0 

### ISSUE THREAD

**Issue by rsignell-usgs** [conda-forge/spyder-feedstock#10]
I created a new environment with the latest python and spyder from conda-forge (`python=3.6` and  `spyder=3.1.3`) and on startup it complained it didn't have `jedi=0.9.0. `
![2017-02-22_14-55-25](https://cloud.githubusercontent.com/assets/1872600/23233848/1dad2088-f91e-11e6-97be-00fe050f9027.png)
  

I did conda list and found out I had jedi=0.10.0 installed.

So I did "conda install jedi=0.9.0" and started up spyder again.

It seems happy.

**Comment by ccordoba12** [comment]
Yes, we had to pin Jedi to 0.9.0 because we need to do some changes to be compatible with 0.10.0

**Comment by ocefpaf** [comment]
@ccordoda12 can you send a PR pinning jedi here? I'm in transit with only a flaky 3G connection.
