### ISSUE TITLE
Release pin on qdarkstyle just a little bit

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/spyder-feedstock#141]
https://github.com/conda-forge/spyder-feedstock/blob/effba1157547709f8c3e4623344e86eb85eaedb3/recipe/meta.yaml#L62

I know that you are quite conservative with pinnings due to the size of this project, but I think it should be pretty safe to release this, unless I am mistaken.

Thank you for considering.

**Comment by ccordoba12** [comment]
This was fixed in PR #143.
