### ISSUE TITLE
macOS packages are not being uploaded to anaconda.org

### ISSUE THREAD

**Issue by ccordoba12** [conda-forge/spyder-feedstock#15]
I don't know what's happening, but I can see this error in Travis:

https://travis-ci.org/conda-forge/spyder-feedstock/jobs/217958856#L2525

Pinging @jakirkham and @ocefpaf about it

**Comment by jakirkham** [comment]
Is that the right build log. The token shouldn't be present in a PR build, but it should be present in a build on the main feedstock.

**Comment by jakirkham** [comment]
It seems to still be building ATM. ( https://travis-ci.org/conda-forge/spyder-feedstock/builds/218115231 )

**Comment by ccordoba12** [comment]
Sorry, I looked at the wrong build page. Sleep deprived here, ignore me :-p

**Comment by jakirkham** [comment]
No worries. Have done the same thing before.
