### ISSUE TITLE
spyder-kernels 0.* Requirement

### ISSUE THREAD

**Issue by JesterEE** [conda-forge/spyder-feedstock#38]
Is there any reason `spyder-kernels` has the requirement of 0.* when conda-forge/spyder-kernels-feedstock@4e29d61a81092d0e7a54473880183bcc6d40c686 is currently at 1.1?

When I try and update packages with `conda update --all` it is first trying to update spyder-kernels to the latest in `conda-forge` thus downgrading spyder to 3.2.8 (conda-forge/spyder-feedstock@5d5506d0d8e79d99d9617e3cf02f54c80f33ca5d) which is the last release that spyder-kernels was not required.

I can pin spyder-kernels to make spyder happy, but I generally don't like pinning things since I forget why I did it in the first place and potentially break future updates.
 
 Thanks!

**Comment by ccordoba12** [comment]
> Is there any reason spyder-kernels has the requirement of 0.*

Yes, there is. That version is required for `spyder >= 3.3; < 4`. `spyder-kernels >= 1.0` is required for `spyder >= 4`.

@kalefranz, why `conda update --all` is failing to solve this requirement correctly?

**Comment by JesterEE** [comment]
@ccordoba12 fair enough.  So I'll just have to hold back spyder-kernels and update spyder till 4.0 is released.  I little annoying for updating everything else, but I can deal with that in the interim.  Thanks!
